---
# To get started with Dependabot version updates, you need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"  # See docs for possible values
    directory: "/Miiworse"  # Location of package manifests
    schedule:
      interval: "monthly"
    labels:
      - enhancement
    groups:
      npm:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - enhancement
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: nuget
    directory: "/Miiworse"
    schedule:
      interval: monthly
    labels:
      - enhancement
    groups:
      nuget:
        patterns:
          - "*"
